version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client

# Soon
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network