version: '3.8'

services:
  client:
    build:
      context: ./client # Путь к директории с Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт для доступа к приложению
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client

# Soon
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - app-network