version: "3.9"
services:
  client:
    build:
      context: ./client
      target: production
    restart: always
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static-files:/usr/share/nginx/html
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-files: