version: "3.9"

services:
  client:
    container_name: app

    build:
      context: ./client
      dockerfile: Dockerfile.prod

    volumes:
      - app_build:/app/build

    networks:
      - app-network

  nginx:
    container_name: static
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app_build:/usr/share/nginx/html
    # depends_on:
      # - client
      # - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
volumes:
  app_build: