name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      
      # Docker
      - name: Build & Run
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d

      # Tests
      # - name: Run tests
      #   run: |
      #     docker-compose exec client npm test

      
      # Exit
      - name: Stop
        run: |
          docker-compose down