name: CI
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Some step 1
        run: echo Тестовый запуск CI
      - name: Some step 2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
